# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropManagement', '0002_auto_20171112_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilreport',
            name='uploaded_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 23, 42, 10, 642715)),
        ),
    ]
