# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropManagement', '0003_auto_20171112_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilreport',
            name='uploaded_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 0, 58, 50, 782943)),
        ),
    ]
